### ISSUE TITLE
RuntimeError: Not enough qubits in circuit to make given placement connected

### ISSUE THREAD

**Issue by darkbtf** [CQCL/pytket#71] opened 2021-04-22 12:05 UTC
I tried to route a QUEKO benchmark circuit on a customized device architecture (works on IBM rochester originally) and got the following error message:

```
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    passes.apply(unit)
RuntimeError: Not enough qubits in circuit to make given placement connected
```

I just make sure the customized device architecture is connected and AFAIK a larger architecture can accommodate smaller circuits, so I have know idea what the "not enough qubits in circuit" means :(

My code is here for reference:
https://github.com/darkbtf/tket-quantum-circuit-routing

**Comment by sjdilkes** [comment] 2021-04-23 12:58
Hi darktbf,

Apologies, this RuntimeError is not clear. I will make sure its updated for clarity before our next release.

To explain, this error is typically thrown under the following circumstance:
* The GraphPlacement method has only completed a partial placement of Qubit objects from tk_circuit to Node objects for tk_device
* The partial placement produced has mapped the logical Qubit’s to multiple distinct subgraph’s of Node’s. Between each distinct subset of Nodes there may be some Nodes without any logical Qubit assigned. These Nodes may have logical Qubits from tk_circuit assigned to them during the Routing procedure.
* Note here that currently routing in tket does not support using Nodes that haven't been assigned a logical qubit
* During routing, if a Qubit in tk_circuit has not yet been assigned a starting Node from tk_device it is assigned one when an operation with this Qubit is first encountered
* This mid-routing placement step prioritises assigning the given logical qubit to a Node that will connect two unconnected subgraph’s of Node’s from the placement procedure
* This RuntimeError is thrown if at this point it finds that the shortest distance between two unconnected (but placed) subgraphs of the Placement is larger than the number of remaining logical qubits to place.

This error was intended to  catch cases where an unsuitable custom defined placement is used for routing. As you are using GraphPlacement before the tket RoutingPass, the error being thrown in this case is unexpected. Unfortunately due to the large size of the circuit you are creating I am unable to quickly find and fix what is causing this error to be thrown so I will leave this issue open for now.

However, as a temporary fix I have found that if you use `pytket.qasm.circuit_from_qasm` to create a pytket `Circuit`  from the qasm file in your repository that this error is not thrown:

```
tk_circuit = circuit_from_qasm("QUEKO-benchmark/BSS/53QBT_700CYC_QSE_9.qasm")
tk_device = _device_connection_list_to_tket_device(device_connection_list)

unit = CompilationUnit(tk_circuit.copy(), [ConnectivityPredicate(tk_device)])

passes = SequencePass(
    [
        PlacementPass(GraphPlacement(tk_device)),
        RoutingPass(tk_device, bridge_lookahead=0, bridge_interactions=0),
    ]
)  # NO BRIDGE
passes.apply(unit)
valid = unit.check_all_predicates()

assert valid
```

**Comment by darkbtf** [comment] 2021-04-25 09:47
The temporary works well for me.

Thanks for your prompt help!

**Comment by cqc-alec** [comment] 2022-02-21 08:11
The referenced `main.py` seems to be using an old version of pytket, However I was able to make a few modifications to work with the [current version](https://github.com/CQCL/pytket-extensions/tree/develop/modules/pytket-cirq) of pytket-cirq.
```python
from pytket.routing import Architecture
from pytket.extensions.cirq import cirq_to_tk, tk_to_cirq

from cirq.contrib.qasm_import import circuit_from_qasm

from pytket.circuit import Node
from pytket.predicates import CompilationUnit, ConnectivityPredicate
from pytket.routing import GraphPlacement
from pytket.passes import SequencePass, RoutingPass, DecomposeSwapsToCXs, PlacementPass


def read_qasm_circuit(path):
    qasm_string = open(path, "r").read()
    try:
        return circuit_from_qasm(qasm_string)
    except:
        print("wrong circuit format")


def _device_connection_list_to_tket_device(device_connection_list):
    return Architecture(device_connection_list)
```
and
```python
tk_circuit = cirq_to_tk(circuit)
tk_device = _device_connection_list_to_tket_device(device_connection_list)

unit = CompilationUnit(tk_circuit, [ConnectivityPredicate(tk_device)])

passes = SequencePass(
    [
        PlacementPass(GraphPlacement(tk_device)),
        RoutingPass(tk_device, bridge_lookahead=0, bridge_interactions=0),
    ]
)  # NO BRIDGE
passes.apply(unit)
valid = unit.check_all_predicates()

assert valid

routed_circuit = tk_to_cirq(unit.circuit)
```
The code then runs successfully.

So it looks like the issue has been fixed.

**Closed by cqc-alec** 2022-02-21 08:11 UTC
Labels: bug
